# Generated by Django 5.2.13 on 2026-04-28 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('location', models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('arcana', models.CharField(blank=True, choices=[('fool', 'Шут'), ('magician', 'Маг'), ('priestess', 'Жрица'), ('empress', 'Императрица'), ('emperor', 'Император'), ('hierophant', 'Иерофант'), ('lovers', 'Влюблённые'), ('chariot', 'Колесница'), ('strength', 'Сила'), ('hermit', 'Отшельник'), ('wheel', 'Колесо Фортуны'), ('justice', 'Справедливость'), ('hanged', 'Повешенный'), ('death', 'Смерть'), ('temperance', 'Умеренность'), ('devil', 'Дьявол'), ('tower', 'Башня'), ('star', 'Звезда'), ('moon', 'Луна'), ('sun', 'Солнце'), ('judgement', 'Суд'), ('world', 'Мир')], max_length=20)),
                ('shadow', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('quest', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('curse', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('element', models.CharField(blank=True, choices=[('fire', 'Огонь'), ('water', 'Вода'), ('air', 'Воздух'), ('earth', 'Земля')], max_length=10)),
                ('totem', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('forbidden_magic', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='users_userfriends_no_self_friendship')],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
